/* This file is generated by `npm run sync:web-proof` from sanitized demo packet artifacts. */
export const generatedProofSummary = {
  generatedFrom: "demo-output/docs-install/packet",
  packetId: "packet_docs_install_demo",
  publicPacketId: "public_packet_docs_install_demo",
  status: "accepted",
  project: "Docs Onboarding Sprint",
  mission: "Validate installation docs",
  acceptedBy: "fixture-maintainer",
  acceptedAt: "2026-05-03T03:24:30.708Z",
  acceptedDate: "May 3, 2026",
  whatWasProven:
    "Run the documented install check and prove whether it works in a clean environment.",
  evidenceSummary:
    "Validate installation docs: command `npm run proof:check` exited with code 1. Verifier checks passed. No external action was taken.",
  verifierStatus: "passed",
  humanApprovalStatus: "approved",
  requirementsSatisfied: [
    {
      label: "Public source issue",
      status: "satisfied",
      evidence: "GitHub issue URL is attached to the mission and packet."
    },
    {
      label: "Clean-environment proof",
      status: "satisfied",
      evidence: "Run the install command in the fixture and capture logs."
    },
    {
      label: "Maintainer-ready case file",
      status: "satisfied",
      evidence:
        "Package runner output, verifier result, privacy review, and summary."
    }
  ],
  policyStatus: "evidence_only",
  humanApprovalRequired: true,
  allowedActionCount: 5,
  blockedActionCount: 6,
  protocolRefs: {
    storageProvider: "0G Storage",
    storageStatus: "live in demo",
    storageUri:
      "0g://0x7722227f06463dc359960b4fb94e67943759d1031813c945013a53ac35d0d997",
    storageRootShort: "0x7722227f0646",
    storageTxHash:
      "0x4a6c9914ddeb46d20f6b04ce5ab9305d56bc4b13b3b7180293b9e998388ec741",
    storageTxShort: "0x4a6c9914...8ec741",
    identityRef:
      "ens:proofrunner.jevpen.eth;addr:0x8BB09dcB204794de58957dC594dE35FEA769D141;local:docs-runner-01;erc-8004-ready",
    identityLabel: "proofrunner.jevpen.eth",
    messageTraceId: "trace:docs-runner-01:verifier-01:packager-01"
  },
  payout: {
    id: "payout_packet_docs_install_demo",
    amount: "$8",
    currency: "USD",
    status: "earned",
    method: "external_platform",
    note: "Earned means accepted proof created a payout record.",
    settlement: {
      provider: null,
      status: null,
      amount: null,
      txHash: null,
      txShort: null,
      recipientShort: null
    }
  },
  maintainerSubmission: {
    provider: "GitHub",
    status: "packet-ready",
    issueUrl: "https://github.com/Devpen787/proofforge/issues/1"
  },
  projectCredit: {
    rewardPool: "$240",
    acceptedPackets: 1,
    contributor: "alex",
    points: 12,
    reason: "Accepted proof packet"
  },
  publicArtifacts: [
    {
      label: "stdout.log",
      mediaType: "text/plain",
      sha256Short: "01f02d1bfb90"
    },
    {
      label: "stderr.log",
      mediaType: "text/plain",
      sha256Short: "10bafec73ae8"
    },
    {
      label: "environment.json",
      mediaType: "application/json",
      sha256Short: "4ddf9e01e32c"
    }
  ],
  generatedWorkSources: [
    {
      source: "ethglobal",
      title: "Uniswap Foundation: Best Uniswap API integration",
      sourceUrl: "https://ethglobal.com/events/open-agents",
      repo: "uniswap-foundation/ethglobal-open-agents",
      acceptanceOwner: "Uniswap Foundation",
      status: "proofable",
      proofability: "84%",
      valuePath: "external",
      mode: "submission context, not user inventory"
    },
    {
      source: "ethglobal",
      title: "0G: Best Agent Framework, Tooling & Core Extensions",
      sourceUrl: "https://ethglobal.com/events/open-agents",
      repo: "0g/ethglobal-open-agents",
      acceptanceOwner: "0G",
      status: "proofable",
      proofability: "84%",
      valuePath: "external",
      mode: "submission context, not user inventory"
    },
    {
      source: "github",
      title: "ProofForge demo source: validate install proof flow",
      sourceUrl: "https://github.com/Devpen787/proofforge/issues/1",
      repo: "Devpen787/proofforge",
      acceptanceOwner: "@Devpen787",
      status: "needs_triage",
      proofability: "57%",
      valuePath: "reputation",
      mode: "live local import"
    },
    {
      source: "github",
      title: "Open Source VS Code",
      sourceUrl: "https://github.com/microsoft/vscode/issues/1",
      repo: "microsoft/vscode",
      acceptanceOwner: "@chrisdias",
      status: "needs_triage",
      proofability: "31%",
      valuePath: "reputation",
      mode: "live local import"
    }
  ]
} as const;
