/* This file is generated by `npm run sync:web-proof` from sanitized demo packet artifacts. */
export const generatedProofSummary = {
  generatedFrom: "demo-output/docs-install/packet",
  packetId: "packet_docs_install_demo",
  publicPacketId: "public_packet_docs_install_demo",
  status: "accepted",
  project: "Docs Onboarding Sprint",
  mission: "Validate installation docs",
  acceptedBy: "fixture-maintainer",
  whatWasProven:
    "Run the documented install check and prove whether it works in a clean environment.",
  evidenceSummary:
    "Validate installation docs: command `npm run proof:check` exited with code 1. Verifier checks passed. No external action was taken.",
  verifierStatus: "passed",
  humanApprovalStatus: "approved",
  requirementsSatisfied: [
    {
      label: "Public source issue",
      status: "satisfied",
      evidence: "GitHub issue URL is attached to the mission and packet."
    },
    {
      label: "Clean-environment proof",
      status: "satisfied",
      evidence: "Run the install command in the fixture and capture logs."
    },
    {
      label: "Maintainer-ready case file",
      status: "satisfied",
      evidence:
        "Package runner output, verifier result, privacy review, and summary."
    }
  ],
  policyStatus: "evidence_only",
  humanApprovalRequired: true,
  allowedActionCount: 5,
  blockedActionCount: 6,
  protocolRefs: {
    storageProvider: "0G Storage",
    storageStatus: "implemented, credential-gated",
    storageUri: null,
    storageRootShort: null,
    storageTxHash: null,
    storageTxShort: null,
    identityRef: "local:docs-runner-01;erc-8004-ready",
    messageTraceId: "trace:docs-runner-01:verifier-01:packager-01"
  },
  payout: {
    id: "payout_packet_docs_install_demo",
    amount: "$8",
    currency: "USD",
    status: "earned",
    method: "external_platform",
    note: "Earned means accepted proof created a payout record."
  },
  projectCredit: {
    rewardPool: "$240",
    acceptedPackets: 1,
    contributor: "alex",
    points: 12,
    reason: "Accepted proof packet"
  },
  publicArtifacts: [
    {
      label: "stdout.log",
      mediaType: "text/plain",
      sha256Short: "01f02d1bfb90"
    },
    {
      label: "stderr.log",
      mediaType: "text/plain",
      sha256Short: "10bafec73ae8"
    },
    {
      label: "environment.json",
      mediaType: "application/json",
      sha256Short: "4d631f376755"
    }
  ],
  generatedWorkSources: []
} as const;
