import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

interface PublicArtifact {
  label: string;
  mediaType: string;
  sha256: string;
}

interface PublicPacket {
  id: string;
  packetId: string;
  status: string;
  project: string;
  mission: string;
  acceptedBy: string;
  whatWasProven: string;
  evidenceSummary: string;
  publicArtifacts: PublicArtifact[];
}

interface Payout {
  id: string;
  amount: number;
  currency: string;
  status: string;
  method: string;
  notes: string[];
}

interface Policy {
  status: string;
  humanApprovalRequired: boolean;
  allowedActions: string[];
  blockedActions: string[];
}

interface EvidencePacket {
  verifierResult: {
    status: string;
  };
  humanApproval: {
    status: string;
  };
}

interface ProjectState {
  rewardPool: number;
  acceptedPacketIds: string[];
  creditLedger: Array<{
    contributor: string;
    points: number;
    reason: string;
  }>;
}

const sourceDir = resolve("demo-output/docs-install/packet");
const outPath = resolve("apps/web/src/generatedProof.ts");

async function readJson<T>(fileName: string): Promise<T> {
  return JSON.parse(await readFile(resolve(sourceDir, fileName), "utf8")) as T;
}

async function main(): Promise<void> {
  const publicPacket = await readJson<PublicPacket>("public-packet.json");
  const payout = await readJson<Payout>("payout.json");
  const policy = await readJson<Policy>("policy.json");
  const evidencePacket = await readJson<EvidencePacket>("evidence-packet.json");
  const project = await readJson<ProjectState>("project.json");
  const credit = project.creditLedger[0];

  const generatedProofSummary = {
    generatedFrom: "demo-output/docs-install/packet",
    packetId: publicPacket.packetId,
    publicPacketId: publicPacket.id,
    status: publicPacket.status,
    project: publicPacket.project,
    mission: publicPacket.mission,
    acceptedBy: publicPacket.acceptedBy,
    whatWasProven: publicPacket.whatWasProven,
    evidenceSummary: publicPacket.evidenceSummary,
    verifierStatus: evidencePacket.verifierResult.status,
    humanApprovalStatus: evidencePacket.humanApproval.status,
    policyStatus: policy.status,
    humanApprovalRequired: policy.humanApprovalRequired,
    allowedActionCount: policy.allowedActions.length,
    blockedActionCount: policy.blockedActions.length,
    payout: {
      id: payout.id,
      amount: `$${payout.amount}`,
      currency: payout.currency,
      status: payout.status,
      method: payout.method,
      note: payout.notes[0]
    },
    projectCredit: {
      rewardPool: `$${project.rewardPool}`,
      acceptedPackets: project.acceptedPacketIds.length,
      contributor: credit?.contributor ?? "unknown",
      points: credit?.points ?? 0,
      reason: credit?.reason ?? "Accepted proof packet"
    },
    publicArtifacts: publicPacket.publicArtifacts.map((artifact) => ({
      label: artifact.label,
      mediaType: artifact.mediaType,
      sha256Short: artifact.sha256.slice(0, 12)
    }))
  };

  const source = [
    "/* This file is generated by `npm run sync:web-proof` from sanitized demo packet artifacts. */",
    "export const generatedProofSummary = " + JSON.stringify(generatedProofSummary, null, 2) + " as const;",
    ""
  ].join("\n");

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, source, "utf8");
  console.log(`Generated web proof data: ${outPath}`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
